apiVersion: v1
kind: Secret
metadata:
  name: jugajug-secrets
  namespace: jugajug-prod
type: Opaque
stringData:
  APP_KEY: "base64:dummyproductionappkey12345678901234567890"
  DB_PASSWORD: "super_secure_db_password"
  REDIS_PASSWORD: "super_secure_redis_password"
  REVERB_APP_SECRET: "reverb_secret_key"
